In [7]:
using(LinearAlgebra)
A = rand(1000, 1000)
x = rand(1000)
b = A*x

1000×1000 Array{Float64,2}:
 0.531074   0.122714   0.764328   …  0.00200093  0.58644     0.805957 
 0.143587   0.42682    0.905587      0.0598392   0.58675     0.150932 
 0.533487   0.502326   0.0530202     0.0978404   0.881388    0.368391 
 0.50761    0.462163   0.327654      0.151982    0.142549    0.996536 
 0.628236   0.694976   0.120884      0.30621     0.0823358   0.963059 
 0.162943   0.456521   0.799513   …  0.926728    0.0240755   0.784808 
 0.124647   0.0930861  0.685793      0.348874    0.231099    0.96562  
 0.407667   0.41977    0.460442      0.540135    0.356887    0.367749 
 0.6409     0.910319   0.0699366     0.361996    0.160656    0.0715206
 0.417463   0.303397   0.593647      0.729698    0.269633    0.743505 
 0.875406   0.929412   0.0380862  …  0.272512    0.732539    0.242182 
 0.233897   0.173134   0.97609       0.673608    0.673606    0.635059 
 0.417356   0.417016   0.9093        0.801744    0.422602    0.45591  
 ⋮                                ⋱              

In [68]:
invX = inv(A) * b
divX = A \ b
AF= factorize(A)
factX =  AF \ b

invTime = @elapsed inv(A) * b
divTime = @elapsed  A \ b
factTime = @elapsed factorize(A)
factTime += @elapsed AF \ b

print("Inverse  time ")
println(invTime)
print("Operator \\ time ")
println(divTime)
print("Factorize time ")
println(factTime)

Inverse  time 0.115862409
Operator \ time 0.093917277
Factorize time 0.095853563


In [69]:
println("Błąd")
print("Inverse ")
invDeltaX = x - invX
println(sqrt(dot(invDeltaX,invDeltaX)))

divDeltaX = x -  divX
print("Operator \\ ")
println(sqrt(dot(divDeltaX,divDeltaX)))

factDeltaX = x - factX

print("Factorize ")
println(sqrt(dot(factDeltaX,factDeltaX)))

Błąd
Inverse 3.162919064607151e-11
Operator \ 1.3582377679316726e-11
Factorize 1.3582377679316726e-11


In [83]:
using CSV
using DataFrames
using Plots
using Polynomials
using Statistics
input="dane.csv"
df=CSV.read(input, delim=";")
df3=by(df, [:size]) do subGroup
          DataFrame(meanNaive = mean(subGroup[:naive]), stdNaive = std(subGroup[:naive]),
            meanBetter = mean(subGroup[:better]), stdBetter = std(subGroup[:better]),
            meanBlas = mean(subGroup[:blas]), stdBlas = std(subGroup[:blas])) 
        end
y = df3[:meanNaive]
x = [100,200,300,400,500,600,700,800]
A=zeros(8,4)
A[:,1] = x.^3
A[:,2] = x.^2
A[:,3] = x
A[:,4] = ones(8)
A \ y


4-element Array{Float64,1}:
  7.344460185185185e-8
 -2.959810833333338e-5
  0.007099599338624374
 -0.5281812857142923  

In [84]:
polyfit(x, y,3)

Poly(-0.5281812857142923 + 0.007099599338624374*x - 2.959810833333338e-5*x^2 + 7.344460185185185e-8*x^3)

In [18]:
using(LinearAlgebra)
A = zeros(4,3)
A[:,1] = [1 1 1 1]
A[:,2] = [-1, 4, 4, -1]
A[:,3] = [4 -2 2 0]

4×3 Array{Float64,2}:
 1.0  -1.0   4.0
 1.0   4.0  -2.0
 1.0   4.0   2.0
 1.0  -1.0   0.0

In [19]:
AF=factorize(A)

QRPivoted{Float64,Array{Float64,2}}
Q factor:
4×4 LinearAlgebra.QRPackedQ{Float64,Array{Float64,2}}:
 -0.171499  -0.800368    0.282843  -0.5
  0.685994   0.315296    0.424264  -0.5
  0.685994  -0.509325   -0.141421   0.5
 -0.171499   0.0242536   0.848528   0.5
R factor:
3×3 Array{Float64,2}:
 5.83095  -0.685994   1.02899 
 0.0      -4.85071   -0.970143
 0.0       0.0        1.41421 
permutation:
3-element Array{Int64,1}:
 2
 3
 1

In [21]:
inv(AF.R)

3×3 Array{Float64,2}:
 0.171499  -0.0242536  -0.141421
 0.0       -0.206155   -0.141421
 0.0        0.0         0.707107

ArgumentError: ArgumentError: number of rows of each array must match (got (3, 1))